spring:
   datasource:
     url: jdbc:mysql://localhost:3306/hibernate
     username: developer
     password: Newdivide
   jpa:
     database: mysql
     show_sql: true
     hibernate:
       ddl-auto: create-drop

