spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/CrudTest
    driverClassName: com.mysql.cj.jdbc.Driver
    username: Developer
    password: Newdivide1
  jpa:
    database: mysql
    show_sql: true
    hibernate:
      ddl-auto: create


---
environment : test
spring:
  datasource:
    url: jdbc:h2:mem:CrudTest
    driverClassName: org.h2.Driver
    username: Developer
    password: Newdivide1
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enable: true